#!/usr/bin/python3
"""
A simple REPL, or read eval print loop.
"""
import sys
sys.path.append("src/")

from romnomnom import exceptions
from romnomnom.interpreter import evaluate

read = input


if __name__ == "__main__":
    while True:
        try:
            # read, eval, print
            print(evaluate(read("> ")))
            # loop ...
        except exceptions.SyntaxException as e:
            print(e)
        except KeyboardInterrupt:
            exit(0)
