#!/usr/bin/python3
"""
A simple REPL, or read eval print loop.
"""
import sys
sys.path.append('src/')

from compiler import read
from compiler import exceptions


if __name__ == "__main__":
    while True:
        try:
            source = input('> ').strip()
            if source:
                # read, eval, print
                print(eval(read(source)))
                # loop ...
        except (exceptions.LexException, exceptions.ParseException) as e:
            print(e)
        except KeyboardInterrupt:
            exit(0)
